name: CI-CD
on: 
  push:
    branches : ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "executar o docker build"
      - run: echo "Enviar a imagem docker para docker hub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "obter codigo"
      - run: echo "configurar kube config"
      - run: echo "executar o apply deployment"
    
